/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dimata.harisma.utility.harisma.machine;

import com.dimata.harisma.session.aplikasidesktop.attendance.SessAplicationDestopAbsensiAttendance;
import com.dimata.harisma.utility.harisma.masterdatadesktop.entity.KonfigurasiMasterOutletSetting;
import com.dimata.harisma.utility.harisma.masterdatadesktop.entity.PstKonfigurasiOutletSetting;
import com.dimata.util.Formater;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimata 007
 */
public class KonfigurationSetting extends javax.swing.JFrame {

    /**
     * Creates new form KonfigurationSetting
     */
    public KonfigurationSetting(KonfigurasiMasterOutletSetting konfigurasiMasterOutletSetting) {
        initComponents();
        //txtLetakMysql.setVisible(false);
        //jLabel3.setVisible(false);
        if (konfigurasiMasterOutletSetting != null) {
            txtLetakMysql.setText(konfigurasiMasterOutletSetting.getUrlLetakMysqlExe());
            txtUsername.setText(konfigurasiMasterOutletSetting.getUsernameMysql());
            txtNamaDb.setText(konfigurasiMasterOutletSetting.getPortMysqlnDbName());
            txtPassword.setText(konfigurasiMasterOutletSetting.getPasswordMysql());
            txtUrlImages.setText(konfigurasiMasterOutletSetting.getUrlImages());
            txtUrlIcon.setText(konfigurasiMasterOutletSetting.getUrlImagesIcon());
            txtPositionId.setText(""+konfigurasiMasterOutletSetting.getOidPositionKonfig()); 
            txtTimeExtraAbsence.setText(""+konfigurasiMasterOutletSetting.getTambahanBolehAbs()); 
        } else {
            long oidKonfiguration = PstKonfigurasiOutletSetting.getOid("", 0, 1);
            konfigurasiMasterOutletSetting = new KonfigurasiMasterOutletSetting();
            if (oidKonfiguration != 0) {
                try {
                    konfigurasiMasterOutletSetting = PstKonfigurasiOutletSetting.fetchExc(oidKonfiguration);
                    txtLetakMysql.setText(konfigurasiMasterOutletSetting.getUrlLetakMysqlExe());
                    txtUsername.setText(konfigurasiMasterOutletSetting.getUsernameMysql());
                    txtNamaDb.setText(konfigurasiMasterOutletSetting.getPortMysqlnDbName());
                    txtPassword.setText(konfigurasiMasterOutletSetting.getPasswordMysql());
                    txtUrlImages.setText(konfigurasiMasterOutletSetting.getUrlImages());
                    txtUrlIcon.setText(konfigurasiMasterOutletSetting.getUrlImagesIcon());
                     txtPositionId.setText(""+konfigurasiMasterOutletSetting.getOidPositionKonfig());
                     txtTimeExtraAbsence.setText(""+konfigurasiMasterOutletSetting.getTambahanBolehAbs()); 
                    SessAplicationDestopAbsensiAttendance.setOidSettingOutlet(oidKonfiguration);
                } catch (Exception e) {
                }
            }
        }
         setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUrlImages = new javax.swing.JTextField();
        txtUrlIcon = new javax.swing.JTextField();
        txtLetakMysql = new javax.swing.JTextField();
        txtNamaDb = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtPositionId = new javax.swing.JTextField();
        jTimeTelat = new javax.swing.JLabel();
        txtTimeExtraAbsence = new javax.swing.JTextField();
        jTimeTelat1 = new javax.swing.JLabel();
        txtAutoDownload = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Url Images");

        jLabel2.setText("Url Images Icon");

        jLabel3.setText("Command");

        jLabel4.setText("Dsn Mysql");

        jLabel5.setText("Username Mysql");

        jLabel6.setText("Password Mysql");

        txtUrlImages.setToolTipText("D:\\\\Dimata\\\\Aplikasi\\\\Absensi\\\\Images");

        txtUrlIcon.setToolTipText("D:\\\\Dimata\\\\Aplikasi\\\\Absensi\\\\images_desktop");

        txtLetakMysql.setToolTipText("jika memakai windows: cmd.exe,/c or linux sh,-c");

        txtNamaDb.setToolTipText("localhost,3306,db_outlet_mm");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Konfiguration Setting Outlet");

        jLabel8.setText("Position Oid");

        jTimeTelat.setText("Jam");

        txtTimeExtraAbsence.setText("1");
        txtTimeExtraAbsence.setToolTipText("masukkan jumlah waktu tambahan awal absensi");

        jTimeTelat1.setText("konf Awal Abs");

        jLabel9.setText("Jam Auto Start (24 Jam)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAutoDownload, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUrlImages)
                            .addComponent(txtUrlIcon)
                            .addComponent(txtLetakMysql, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaDb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword)
                            .addComponent(txtPositionId)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimeExtraAbsence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTimeTelat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jTimeTelat1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtUrlImages, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLetakMysql, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaDb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPositionId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutoDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTimeTelat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeExtraAbsence, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addGap(6, 6, 6))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(347, Short.MAX_VALUE)
                    .addComponent(jTimeTelat1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        KonfigurasiMasterOutletSetting konfigurasiMasterOutletSetting = new KonfigurasiMasterOutletSetting();
        int getCount = PstKonfigurasiOutletSetting.getCount("");
        //long oidKonfiguration = PstKonfigurasiOutletSetting.getOid("", 0, 1);
      //  String letakMysql = txtLetakMysql.getText();
       /* if (letakMysql != null) {
            letakMysql = letakMysql.replace("\\", "\\\\");
        }*/
        konfigurasiMasterOutletSetting.setUrlLetakMysqlExe(txtLetakMysql.getText());
        konfigurasiMasterOutletSetting.setUsernameMysql(txtUsername.getText());
        konfigurasiMasterOutletSetting.setPortMysqlnDbName(txtNamaDb.getText());
        konfigurasiMasterOutletSetting.setPasswordMysql(txtPassword.getText());
        konfigurasiMasterOutletSetting.setUrlImages(txtUrlImages.getText());
        konfigurasiMasterOutletSetting.setUrlImagesIcon(txtUrlIcon.getText());
        konfigurasiMasterOutletSetting.setOidPositionKonfig(txtPositionId.getText()!=null && txtPositionId.getText().length()>0 ?(txtPositionId.getText()):"0");
        konfigurasiMasterOutletSetting.setAutoStart(txtAutoDownload.getText());
        konfigurasiMasterOutletSetting.setTambahanBolehAbs(txtTimeExtraAbsence.getText()!=null?Integer.parseInt(txtTimeExtraAbsence.getText()) :0);


        long oid = 0;

        try {
            if (getCount == 0) {
                oid = PstKonfigurasiOutletSetting.insertExc(konfigurasiMasterOutletSetting);
            } else {
                konfigurasiMasterOutletSetting.setOID(SessAplicationDestopAbsensiAttendance.getOidSettingOutlet());
                oid = PstKonfigurasiOutletSetting.updateExc(konfigurasiMasterOutletSetting);
            }

            if (oid != 0) {
                JOptionPane.showMessageDialog(null, "<html> save sukses, please logout now </html>", "Inane warning", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "<html> save not sukses </html>", "Inane warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "" + exc, "Inane warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfigurationSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfigurationSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfigurationSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfigurationSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfigurationSetting(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jTimeTelat;
    private javax.swing.JLabel jTimeTelat1;
    private javax.swing.JTextField txtAutoDownload;
    private javax.swing.JTextField txtLetakMysql;
    private javax.swing.JTextField txtNamaDb;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPositionId;
    private javax.swing.JTextField txtTimeExtraAbsence;
    private javax.swing.JTextField txtUrlIcon;
    private javax.swing.JTextField txtUrlImages;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
