/* Generated by Together */

package com.dimata.harisma.entity.search;

/* package java */ 
import java.util.Date;

public class SrcMedicalRecord {

	private int startRecordDate_yr=0;
	private int startRecordDate_mn=0;
	private int startRecordDate_dy=0;
	private int endRecordDate_yr=0;
	private int endRecordDate_mn=0;
	private int endRecordDate_dy=0;
	private long employeeId = 0;
	private long diseaseTypeId = 0;
	private long medicalTypeId = 0;
    private int orderBy;
    private Date startDate;
    private Date endDate;
    private long departmentId;
    private long medicalCaseId;

	public int getStartRecordDate_yr(){
		return startRecordDate_yr;
	} 

	public void setStartRecordDate_yr(int startRecordDate_yr){
		this.startRecordDate_yr = startRecordDate_yr;
	} 

	public int getStartRecordDate_mn(){
		return startRecordDate_mn;
	} 

	public void setStartRecordDate_mn(int startRecordDate_mn){
		this.startRecordDate_mn = startRecordDate_mn;
	} 

	public int getStartRecordDate_dy(){
		return startRecordDate_dy;
	} 

	public void setStartRecordDate_dy(int startRecordDate_dy){
		this.startRecordDate_dy = startRecordDate_dy;
	} 

	public int getEndRecordDate_yr(){
		return endRecordDate_yr;
	} 

	public void setEndRecordDate_yr(int endRecordDate_yr){
		this.endRecordDate_yr = endRecordDate_yr;
	} 

	public int getEndRecordDate_mn(){
		return endRecordDate_mn;
	} 

	public void setEndRecordDate_mn(int endRecordDate_mn){
		this.endRecordDate_mn = endRecordDate_mn;
	} 

	public int getEndRecordDate_dy(){
		return endRecordDate_dy;
	} 

	public void setEndRecordDate_dy(int endRecordDate_dy){
		this.endRecordDate_dy = endRecordDate_dy;
	} 
	/*public Date getEndRecordDate(){
		return endRecordDate;
	} 

	public void setEndRecordDate(Date recordDate){
		this.endRecordDate = endRecordDate;
	}*/

    public long getEmployeeId(){
		return employeeId;
	} 

	public void setEmployeeId(long employeeId){
		this.employeeId = employeeId;
	}

	public long getDiseaseTypeId(){
		return diseaseTypeId;
	} 

	public void setDiseaseTypeId(long diseaseTypeId){
		this.diseaseTypeId = diseaseTypeId;
	} 

	public long getMedicalTypeId(){
		return medicalTypeId;
	} 

	public void setMedicalTypeId(long medicalTypeId){
		this.medicalTypeId = medicalTypeId;
	} 

	public int getOrderBy(){
		return orderBy;
	} 

	public void setOrderBy(int orderBy){
		this.orderBy = orderBy;
	} 

    public Date getStartDate(){ return startDate; }

    public void setStartDate(Date startDate){ this.startDate = startDate; }

    public Date getEndDate(){ return endDate; }

    public void setEndDate(Date endDate){ this.endDate = endDate; }

    public long getDepartmentId(){ return departmentId; }

    public void setDepartmentId(long departmentId){ this.departmentId = departmentId; }

    public long getMedicalCaseId() {
        return medicalCaseId;
    }

    public void setMedicalCaseId(long medicalCaseId) {
        this.medicalCaseId = medicalCaseId;
    }
}
