/* Generated by Together */

package com.dimata.harisma.entity.search;

import java.util.Date;


public class SrcTrainingTarget {
    
    private long departmentId = 0;
    private Date month = new Date();
    private int typeOfSearch = 0;
    private int sortBy = 0;

    
    public long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(long departmentId) {
        this.departmentId = departmentId;
    }

    public Date getMonth() {
        return month;
    }

    public void setMonth(Date month) {
        this.month = month;
    }

    public int getSortBy() {
        return sortBy;
    }

    public void setSortBy(int sortBy) {
        this.sortBy = sortBy;
    }

    public int getTypeOfSearch() {
        return typeOfSearch;
    }

    public void setTypeOfSearch(int typeOfSearch) {
        this.typeOfSearch = typeOfSearch;
    }
       
}
