/* Generated by Together */

package com.dimata.util.lang;

import java.util.Hashtable;

public interface I_Language {

    public static int LANGUAGE_DEFAULT   = 0;
    public static int LANGUAGE_FOREIGN   = 1;

    public static String[] langName = {"Indonesia", "English"};
  
    

}
